apiVersion: gravitee.io/v1alpha1
kind: ApiV4Definition
metadata:
  name: generated-crd
  namespace: default
spec:
  name: Petstore API
  description: A sample API to illustrate OpenAPI concepts
  version: 1.0.0
  type: PROXY
  definitionContext:
    origin: KUBERNETES
    syncFrom: MANAGEMENT
  contextRef:
    name: management-context-1
    namespace: default
  listeners:
    - type: HTTP
      paths:
        - path: /petstore
      entrypoints:
        - type: http-proxy
          qos: AUTO
  endpointGroups:
    - name: Default HTTP proxy group
      type: http-proxy
      endpoints:
        - name: Default HTTP proxy
          type: http-proxy
          inheritConfiguration: false
          configuration:
            target: https://api.gravitee.io/echo
          secondary: false
  flowExecution:
    mode: DEFAULT
    matchRequired: false
  plans:
    API_KEY:
      name: API Key plan
      description: API key plan needs a key to authenticate
      security:
        type: API_KEY
      flows: []
  flows:
    - name: Returns a list of stuff
      enabled: true
      selectors:
        - type: HTTP
          path: /list
          pathOperator: EQUALS
          methods:
            - GET
    - name: Create a new Pet
      enabled: true
      selectors:
        - type: HTTP
          path: /pets
          pathOperator: EQUALS
          methods:
            - POST
  resources:
    name: OpenAPI Specification
    type: content-provider-inline-resource
    configuration:
      content: >-
        %7B%22openapi%22%3A%223.1.0%22%2C%22info%22%3A%7B%22version%22%3A%221.0.0%22%2C%22title%22%3A%22Petstore%20API%22%2C%22description%22%3A%22A%20sample%20API%20to%20illustrate%20OpenAPI%20concepts%22%7D%2C%22paths%22%3A%7B%22/list%22%3A%7B%22get%22%3A%7B%22description%22%3A%22Returns%20a%20list%20of%20stuff%22%2C%22responses%22%3A%7B%22200%22%3A%7B%22description%22%3A%22Successful%20response%22%7D%7D%7D%7D%2C%22/pets%22%3A%7B%22post%22%3A%7B%22description%22%3A%22Create%20a%20new%20Pet%22%2C%22responses%22%3A%7B%22201%22%3A%7B%22description%22%3A%22Created%22%7D%7D%7D%7D%7D%7D
    enabled: true
