apiVersion: gravitee.io/v1alpha1
kind: ApiV4Definition
metadata:
  name: generated-crd
  namespace: default
spec:
  name: Petstore API
  description: A sample API to illustrate OpenAPI concepts
  version: 1.0.0
  type: PROXY
  definitionContext:
    origin: KUBERNETES
    syncFrom: MANAGEMENT
  contextRef:
    name: management-context-1
    namespace: default
  listeners:
    - type: HTTP
      paths:
        - path: /petstore
      entrypoints:
        - type: http-proxy
          qos: AUTO
  endpointGroups:
    - name: Default HTTP proxy group
      type: http-proxy
      endpoints:
        - name: Default HTTP proxy
          type: http-proxy
          inheritConfiguration: false
          configuration:
            target: https://api.gravitee.io/echo
          secondary: false
  flowExecution:
    mode: DEFAULT
    matchRequired: false
  plans:
    API_KEY:
      name: API Key plan
      description: API key plan needs a key to authenticate
      security:
        type: API_KEY
      flows: []
  flows:
    - name: OpenAPI Specification Validation
      enabled: true
      selectors:
        - type: HTTP
          path: /
          pathOperator: STARTS_WITH
      request:
        - name: OpenAPI Specification Validation
          enabled: true
          policy: oas-validation
          configuration:
            resourceName: OpenAPI Specification
      response:
        - name: OpenAPI Specification Validation
          enabled: true
          policy: oas-validation
          configuration:
            resourceName: OpenAPI Specification
    - name: Returns a list of stuff
      enabled: true
      selectors:
        - type: HTTP
          path: /list
          pathOperator: EQUALS
          methods:
            - GET
    - name: Create a new Pet
      enabled: true
      selectors:
        - type: HTTP
          path: /pets
          pathOperator: EQUALS
          methods:
            - POST
  resources:
    - name: OpenAPI Specification
      type: content-provider-inline-resource
      configuration:
        content: |
          \ "openapi: 3.1.0 \
          \ info: \
          \   version: 1.0.0 \
          \   title: Petstore API \
          \   description: A sample API to illustrate OpenAPI concepts \
          \ paths: \
          \   /list: \
          \     get: \
          \       description: Returns a list of stuff \
          \       responses: \
          \         '200': \
          \           description: Successful response \
          \   /pets: \
          \     post: \
          \       description: Create a new Pet \
          \       responses: \
          \         '201': \
          \           description: Created \
          \ " \
      enabled: true
