openapi: 3.1.0
info:
  version: 1.0.0
  title: Petstore API
  description: A sample API to illustrate OpenAPI concepts
paths:
  /:
    get:
      description: Root path for only Echo response 
      content:
        application/json:
          schema:
            type: object
            properties:
              id:
                type: integer
                description: The user ID.
              username:
                type: string
                description: The user name.
      responses:
        '200':
          description: Successful response
  /list:
    get:
      description: Returns a list of stuff              
      responses:
        '200':
          description: Successful response
  /pets:
    post:
      description: Create a new Pet             
      responses:
        '201':
          description: Created
