openapi: 3.1.0
info:
  version: 1.0.0
  title: Petstore API
  description: A sample API to illustrate OpenAPI concepts
paths:
  /:
    get:
      description: Root path for only Echo response 
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  bodySize:
                    type: string
                    description: The user ID.
                  headers:
                    type: string
                    description: The user name.
                  query_params:
                    type: string
                    description: Something else.
  /list:
    get:
      description: Returns a list of stuff              
      responses:
        '200':
          description: Successful response
  /pets:
    post:
      description: Create a new Pet             
      responses:
        '201':
          description: Created
